### ISSUE TITLE
Binding x:Static NRE

### ISSUE THREAD

**Issue by xmedeko** [Alex141/CalcBinding#31]
I have working Binging

``` xml
<TextBlock Visibility="{Binding Source={x:Static myProp:Settings.BoolSetting}, Converter={StaticResource BooleanToVisibilityConverter}}" />
```

However, the CalcBinding fail

``` xml
<TextBlock Visibility="{cb:Binding Source={x:Static myProp:Settings.BoolSetting}" />
```

with

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at CalcBinding.Binding.NormalizePath(String path)
   at CalcBinding.Binding.ProvideValue(IServiceProvider serviceProvider)
```

**Comment by Alex141** [comment]
Beginning with version 2.3.0.0, CalcBinding supports using of [static properties] (https://github.com/Alex141/CalcBinding#2-static-properties), I propose it can solve your task
